<?php

//  
// process the study name in database
//

// connect to the database
include "./connect_pg.php";

@$conn = connect_pg("MIRISK");

if(!$conn){
   echo "Fail to connect to the database";
   exit();
}

$sql = "select oid, study_name from studydata";
$res = pg_query($conn,$sql) or die("fail to insert the data");

$rownum = pg_num_rows($res);

?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title>MIRISK - selectstudy.phtml</title>
  <meta name="description" content="Mitigation Information and Risk Identification System">
  <meta name="author" content="MIRISK Team">
  <meta name="keywords" content="MIRISK">
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <meta name="abstract" content="MIRISK">
  <meta name="description" content="MIRISK">
  <meta name="keywords" content="MIRISK">
  <link href="../dbstyle.css" rel="stylesheet" type="text/css">
</head>

<body>
<center>

<H3>Please Select a Project</H3>

<form method="post" action="./loadstudy.phtml" target="input">
<select name="selectstudy">

<?php

   for($i=0;$i<$rownum;$i++)
   {
     $arr = pg_fetch_row($res,$i);
     echo "<option value=$arr[0]>";
     echo $arr[1];
     echo "</option>";
   }
 
?>  
 
</select>
<BR><BR>
  
<input type="submit" name="loadstudy" value="Load Project">
</form>

<BR>
<I>
<?php echo "Number of stored projects: ", $rownum; ?>
</I>

</center> 
</body>

</html>
